// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8a-qbiCWWm1IEcY82C0vl80ouA7Qo80',
    appId: '1:943063434193:web:eba295986f07686baf16f0',
    messagingSenderId: '943063434193',
    projectId: 'reddit-clone-a2400',
    authDomain: 'reddit-clone-a2400.firebaseapp.com',
    storageBucket: 'reddit-clone-a2400.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCx3c-qkO2ot1C7e2UnDJCYwF6oYwOzE',
    appId: '1:943063434193:android:52a02b27f527a495af16f0',
    messagingSenderId: '943063434193',
    projectId: 'reddit-clone-a2400',
    storageBucket: 'reddit-clone-a2400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnzQ2JyokE2zlTzm6HCHOHp3iCNeFxgMY',
    appId: '1:943063434193:ios:9d515e8cae7cbf6daf16f0',
    messagingSenderId: '943063434193',
    projectId: 'reddit-clone-a2400',
    storageBucket: 'reddit-clone-a2400.appspot.com',
    iosClientId: '943063434193-t9vbdql53v2ktim5v5eoa8udg0qk4p63.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
